audio.ac3.passthrough.if.possible=false
audio.cbr.value=160k
audio.codec=vorbis
audio.enc.is.CBR=true
audio.preferred.channels=5.1
audio.preferred.frequency=48000
profile.name=Webm (high-quality)
video.VBR.value=18
video.aspect.ratio=16\:9
video.aspect.size=HD720p
video.codec=libvpx
video.container=webm
video.enc.is.VBR=true
video.frame.rate=Same as source
video.two.pass.encoding=false
vp8.cpu.threads=1
vp8.max.quant=42
vp8.min.quant=10
vp8.quality.profile=best
vp8.use.cpu=3
