name: rencoder 
base: core18 
version: '1.3.0' 
summary: Rencoder is a friendly front-end for FFmpeg
description: |
  Rencoder is a software package developed in Java language to be a front-end for FFmpeg. 
  This tool can be used to convert a wide range of video formats that are supported by FFmpeg.

grade: stable
confinement: strict

architectures: [amd64]

build-packages: [gcc, g++, make]

parts:
  rencoder:
    source: .
    plugin: dump
    stage-packages:
       - openjdk-8-jdk
       - xdg-utils
       - xdg-desktop-portal

  gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - build-essential    
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - desktop-file-utils
      - ibus-gtk3
      - libibus-1.0-5

  xdg-open:
    after: [rencoder]
    plugin: nil
    source: .
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      install -m 644 mimeapps.list $SNAPCRAFT_PART_INSTALL/usr/share/applications
    build-packages:
      - desktop-file-utils

  shared-mime-info:
    after: [xdg-open]
    plugin: nil
    stage-packages:
      - shared-mime-info
    override-build: |
      set -eux
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime

apps:
  rencoder:
      command: desktop-launch $SNAP/rencoder/rencoder.sh
      plugs: [home, unity7, network, network-observe, network-bind, desktop, desktop-legacy, x11, opengl, removable-media]
      environment: 
          JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-$SNAP_ARCH
          PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH      
